name = "badminton-scheduler-api"
main = "src/index.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "SCHEDULES"
id = "0bd932cd779942858e051712755f4cee"

[[durable_objects.bindings]]
name = "SCHEDULE_ROOMS"
class_name = "ScheduleRoom"

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ScheduleRoom"]

[vars]
SHOW_COUNTRY_LABELS = "false"
